file_format: "1"
id: xryue60
name: xryue60
type: shield
url: https://oshwhub.com/joba
requires: [nrfmicro_13_52840]
features:
  - keys
  - display
  - studio
siblings:
  - xryue60_left
  - xryue60_right
